### ISSUE TITLE
The cursor will frequently defocus the Koikatsu window, requiring the user to go to their computer and reselect the Koikatsu window

### ISSUE THREAD

**Issue by glencoe2004** [mosirnik/KK_MainGameVR#28]
This happens most often when the game is loading or stutters, and can get extremely aggravating very fast.

**Comment by mosirnik** [comment]
That sounds problematic! I need more information to debug this though, because I've been unable to reproduce it.

In particular:

* Is your mouse cursor confined within the Koikatsu window while this plugin is active? You shouldn't be able to move it out with mouse. If you can, something is wrong.
* Is your Koikatsu window covered by something else, like another app or the Windows task bar?
* Is there a particular controller mode (Menu/Warp/School) and/or a particular button press that tend to trigger this? Or does this happen without any action from you?

**Comment by glencoe2004** [comment]
> That sounds problematic! I need more information to debug this though, because I've been unable to reproduce it.
> 
> In particular:
> 
> * Is your mouse cursor confined within the Koikatsu window while this plugin is active? You shouldn't be able to move it out with mouse. If you can, something is wrong.
> * Is your Koikatsu window covered by something else, like another app or the Windows task bar?
> * Is there a particular controller mode (Menu/Warp/School) and/or a particular button press that tend to trigger this? Or does this happen without any action from you?

Alright, going off of memory because I won't be able to use my PC until later:

> * Is your mouse cursor confined within the Koikatsu window while this plugin is active? You shouldn't be able to move it out with mouse. If you can, something is wrong.

Yeah, the cursor is confined to the Koikatsu window on the PC.

> * Is your Koikatsu window covered by something else, like another app or the Windows task bar?

It shouldn't be, although it always defocuses to my browser (likely because it's the app that is behind the koikatsu window)

> * Is there a particular controller mode (Menu/Warp/School) and/or a particular button press that tend to trigger this? Or does this happen without any action from you?

Thinking about it further, I think this happens when the player is moving the mouse cursor in Menu mode right around the edges of the screen, then the game'll lag and lose focus. The cursor still appears grey and highlighted in the headset, but on the computer it'll be on another window.

**Comment by mosirnik** [comment]
Thank you for the information. It sounds like somehow the plugin is generating simulated clicks outside the window...

One more question: how do you move the cursor in the game? Do you use the virtual laser pointer (the documented way), or do you use the touchpad/thumbstick with the Menu tool?

**Comment by glencoe2004** [comment]
I use both, although virtual laser pointer does this more often (and I use it more often).

**Comment by mosirnik** [comment]
Thanks, I'll try to figure out what is going on. In the meantime, starting Koikatsu in fullscreen might help.

**Comment by glencoe2004** [comment]
Unfortunately, I already start the game in fullscreen. Although, now I wonder if windowed suffers from the same bug...

**Comment by mosirnik** [comment]
Could it be that your browser sends out notification messages while you play Koikatsu? If it does, the notification window may get clicked when the plugin attempts to make a fake mouse click.

I confirmed that this can actually happen with Edge, but not with Firefox. Currently I'm unable to test Chrome because my Windows decided not to show notifications from it after I let it spam my desktop with about 300 notifications. Which browser are you using?

I'll write some code to work around this issue, but in the meantime, you can try configuring the Focus Assist feature of Windows to block notifications when you are on a fullscreen app (apparently Koikatsu doesn't qualify as a game, but it's still recognized as a full-screen app).

**Comment by mosirnik** [comment]
Actually it's not that easy to work around this. I'll need to think about how to do it.

**Comment by glencoe2004** [comment]
If it’s still helpful, I use a chromium based browser called Vivaldi. I don’t think its notifications though - I’ve never gotten 10 notifications in 5 minutes before.

Still, I’ll try the focus assist thing.

**Comment by mosirnik** [comment]
> I don’t think its notifications though - I’ve never gotten 10 notifications in 5 minutes before.

In that case, I'm not sure what is going on. Perhaps the plugin should stop faking system-level mouse clicks (it's inherently fragile, as you can never eliminate the possibility of accidentally clicking the wrong window).

**Comment by mosirnik** [comment]
@glencoe2004 I made an experimental version of the plugin that uses a totally different way of simulating mouse clicks. Would you mind giving it a try?

Also let me know if you encounter a warning message at the top left corner of the in-game screen saying that the game window has lost focus.

[KK_MainGameVR-0.11.0-7239c.zip](https://github.com/mosirnik/KK_MainGameVR/files/6918436/KK_MainGameVR-0.11.0-7239c.zip)

**Comment by mosirnik** [comment]
Never mind, this approach seems to have its own set of problems (sigh).

**Comment by mosirnik** [comment]
It turns out that Windows temporarily defocuses a window if it's been unresponsive for a set amount of time. Version 0.12.0 of this plugin disables the feature, which might be helpful.

**Comment by mosirnik** [comment]
@glencoe2004 Any updates?

**Comment by glencoe2004** [comment]
A friend is using my headset for a bit. I’ll try the new update when he gives it back to me.

**Comment by mosirnik** [comment]
The new input injection system should work fine with the window defocused, so this should no longer be an issue.
